name: low_pass_analysis
channels:
  - bioconda
  - defaults
dependencies:
  - bioconductor-biobase=2.34.0=r3.3.2_0
  - bioconductor-biocgenerics=0.22.0=r3.3.2_0
  - bioconductor-biocparallel=1.6.6=r3.3.2_1
  - bioconductor-biostrings=2.42.1=r3.3.2_0
  - bioconductor-cghbase=1.32.0=r3.3.2_1
  - bioconductor-cghcall=2.34.1=r3.3.2_0
  - bioconductor-dnacopy=1.48.0=r3.3.2_0
  - bioconductor-genomeinfodb=1.10.3=r3.3.2_0
  - bioconductor-genomicranges=1.26.4=r3.3.2_0
  - bioconductor-impute=1.46.0=r3.3.2_1
  - bioconductor-iranges=2.8.2=r3.3.2_0
  - bioconductor-limma=3.30.13=r3.3.2_0
  - bioconductor-marray=1.50.0=r3.3.2_1
  - bioconductor-qdnaseq=1.10.0=r3.3.2_0
  - bioconductor-rsamtools=1.26.1=r3.3.2_0
  - bioconductor-s4vectors=0.12.2=r3.3.2_0
  - bioconductor-xvector=0.14.1=r3.3.2_0
  - bioconductor-zlibbioc=1.20.0=r3.3.2_1
  - r-digest=0.6.12=r3.3.2_0
  - r-futile.logger=1.4.1=r3.3.2_0
  - r-futile.options=1.0.0=r3.3.2_0
  - r-ggplot2=2.2.1=r3.3.2_0
  - r-lambda.r=1.1.7=r3.3.2_0
  - r-matrixstats=0.51.0=r3.3.2_1
  - r-scales=0.4.1=r3.3.2_1
  - r-snow=0.4_1=r3.3.2_0
  - r-snowfall=1.84_6.1=r3.3.2_0
  - r-tibble=1.2=r3.3.2_1
  - _r-mutex=1.0.0=anacondar_1
  - bzip2=1.0.6=3
  - cairo=1.14.8=0
  - curl=7.54.1=0
  - fontconfig=2.12.1=3
  - freetype=2.5.5=2
  - glib=2.50.2=1
  - gsl=2.2.1=0
  - harfbuzz=0.9.39=2
  - icu=54.1=0
  - jbig=2.1=0
  - jpeg=9b=0
  - krb5=1.13.2=0
  - libffi=3.2.1=1
  - libgcc=5.2.0=0
  - libiconv=1.14=0
  - libpng=1.6.30=1
  - libssh2=1.8.0=0
  - libtiff=4.0.6=3
  - libxml2=2.9.4=0
  - ncurses=5.9=10
  - openssl=1.0.2l=0
  - pango=1.40.3=1
  - pcre=8.39=1
  - pixman=0.34.0=0
  - r-assertthat=0.1=r3.3.2_4
  - r-base=3.3.2=1
  - r-bitops=1.0_6=r3.3.2_2
  - r-colorspace=1.3_1=r3.3.2_0
  - r-dichromat=2.0_0=r3.3.2_2
  - r-gtable=0.2.0=r3.3.2_0
  - r-labeling=0.3=r3.3.2_2
  - r-lazyeval=0.2.0=r3.3.2_0
  - r-magrittr=1.5=r3.3.2_2
  - r-mass=7.3_45=r3.3.2_0
  - r-munsell=0.4.3=r3.3.2_0
  - r-plyr=1.8.4=r3.3.2_0
  - r-r.methodss3=1.7.1=r3.3.2_0
  - r-r.oo=1.21.0=r3.3.2_0
  - r-r.utils=2.5.0=r3.3.2_0
  - r-rcolorbrewer=1.1_2=r3.3.2_3
  - r-rcpp=0.12.8=r3.3.2_0
  - r-rcurl=1.95_4.8=r3.3.2_0
  - r-reshape2=1.4.2=r3.3.2_0
  - r-stringi=1.1.2=r3.3.2_0
  - r-stringr=1.1.0=r3.3.2_0
  - readline=6.2=2
  - tk=8.5.18=0
  - xz=5.2.3=0
  - zlib=1.2.11=0
